### ISSUE TITLE
COMPILE_WARNINGS_AS_ERRORS typo

### ISSUE THREAD

**Issue by ascheglov** [angohr/angohr#1]
Hi, I noticed that you use "COMPILE_WARNINGS_AS_ERRORS" (plural warnings, plural errors) when the actual property uses non-plural https://cmake.org/cmake/help/latest/prop_tgt/COMPILE_WARNING_AS_ERROR.html

Have a nice day :)

**Comment by cryos** [comment]
Ah thank you I had missed that, just a toy project right now, I appreciate the extra eyes and the bug report.

**Comment by cryos** [comment]
This is now fixed, I checked with `ninja -v` to look at the actual compiler flags. Thanks!
